apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-ingress.yaml
  - namespace.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - secretproviderclass.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - migration-job.yaml
  - scheduler-deployment.yaml
  - worker-deployment.yaml
  - backend-pdb.yaml
  - worker-pdb.yaml
  - backend-hpa.yaml
  - worker-hpa.yaml
  - backend-networkpolicy.yaml
