apiVersion: v1
kind: ServiceAccount
metadata:
  name: uptimehub-app
  namespace: uptimehub-dev
  annotations:
    azure.workload.identity/client-id: "30e35826-ce23-4087-932a-7d321df92625"
  labels:
    azure.workload.identity/use: "true"
