global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alerts.yml


scrape_configs:
  - job_name: uptimehub-backend
    metrics_path: /metrics

    static_configs:
      - targets:
          - backend:8000


  - job_name: uptimehub-worker
    metrics_path: /metrics

    static_configs:
      - targets:
          - worker:9101


  - job_name: uptimehub-scheduler
    metrics_path: /metrics

    static_configs:
      - targets:
          - scheduler:9102
